"""
DFTIKTOK — TikTok search / hashtag scraper
==========================================
A real headless-browser scraper that opens TikTok's search page, lets TikTok's
own JavaScript render the results (and do its own request signing), then
extracts the resulting video URLs from the DOM.

Why a browser? TikTok's search API (`/api/search/general/full/`, hashtag detail,
etc.) requires an `X-Bogus` request signature that is generated by obfuscated
JavaScript on the page — plain HTTP scraping of those endpoints returns empty.
A real (headless) browser sidesteps that by running TikTok's own signer.

Honest limitations (read this):
- TikTok **detects datacenter IPs and headless browsers** and shows a CAPTCHA.
  From this sandbox (a datacenter IP) search will hit the captcha and return
  nothing. Self-hosting on a **residential / normal ISP IP** (your own machine
  or a home-server) makes this work reliably.
- No scraper can be guaranteed 100% forever — TikTok actively changes its
  anti-bot rules. This module is written defensively and fails *gracefully*
  (returns a clear message) instead of crashing.

Usage
-----
    from scraper import search_tiktok
    urls = search_tiktok("cat", max_results=10)
    # -> ["https://www.tiktok.com/@user/video/123...", ...]
"""

from __future__ import annotations

import re
import time
from typing import List, Optional

_CACHE: dict = {}          # query -> (timestamp, urls)
_CACHE_TTL = 5 * 60        # 5 minutes

UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

_STEALTH_JS = """
Object.defineProperty(navigator,'webdriver',{get:()=>undefined});
Object.defineProperty(navigator,'languages',{get:()=>['id-ID','id','en-US','en']});
Object.defineProperty(navigator,'plugins',{get:()=>[1,2,3,4,5]});
window.chrome = { runtime: {} };
"""

_LINK_RE = re.compile(r"/(@[A-Za-z0-9_.-]+/(?:video|photo)/\d{15,})")

IS_CAPTCHA_PATTERNS = ("captcha", "verify", "challenge")


class ScraperError(Exception):
    """Raised when scraping fails for a known, explainable reason."""


def _looks_like_captcha(html: str) -> bool:
    low = html.lower()
    return any(p in low for p in IS_CAPTCHA_PATTERNS)


def search_tiktok(query: str, max_results: int = 10, timeout_ms: int = 30000) -> List[str]:
    """Search TikTok for videos matching `query`.

    `query` may be a keyword ("cat") or a hashtag ("#fyp" / "fyp" — the '#'
    is stripped). Returns a list of full TikTok URLs.
    """
    query = (query or "").strip().lstrip("#")
    if not query:
        return []

    cached = _CACHE.get(query)
    if cached and time.time() - cached[0] < _CACHE_TTL:
        return cached[1]

    urls = _search_with_browser(query, max_results, timeout_ms)
    if urls:
        _CACHE[query] = (time.time(), urls)
    return urls


def _search_with_browser(query: str, max_results: int, timeout_ms: int) -> List[str]:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        raise ScraperError(
            "Scraper belum diinstal. Jalankan: pip install playwright && playwright install chromium"
        ) from exc

    try:
        with sync_playwright() as p:
            try:
                browser = p.chromium.launch(
                    headless=True,
                    args=[
                        "--no-sandbox",
                        "--disable-blink-features=AutomationControlled",
                        "--disable-dev-shm-usage",
                    ],
                )
            except Exception as exc:
                raise ScraperError(
                    f"Gagal meluncurkan Chromium (perlu `playwright install chromium`): {exc}"
                ) from exc

            try:
                ctx = browser.new_context(
                    user_agent=UA,
                    viewport={"width": 1366, "height": 900},
                    locale="id-ID",
                    extra_http_headers={"Accept-Language": "id-ID,id;q=0.9,en;q=0.8"},
                )
                ctx.add_init_script(_STEALTH_JS)
                page = ctx.new_page()

                url = "https://www.tiktok.com/search/video?q=" + query
                page.goto(url, wait_until="domcontentloaded", timeout=timeout_ms)
                # let the client-side search render
                page.wait_for_timeout(7000)

                html = page.content()
                if _looks_like_captcha(html):
                    raise ScraperError(
                        "TikTok menampilkan CAPTCHA (IP datacenter/headless terdeteksi). "
                        "Self-host di IP residensial agar pencarian berfungsi."
                    )

                links = sorted(set(_LINK_RE.findall(html)))
                urls = ["https://www.tiktok.com" + l for l in links[:max_results]]
                return urls
            finally:
                browser.close()
    except ScraperError:
        raise
    except Exception as exc:
        raise ScraperError(f"Scraper error: {exc}") from exc


def available() -> bool:
    """True if Playwright + Chromium are installed and usable."""
    try:
        import playwright  # noqa: F401
        return True
    except ImportError:
        return False
